export type Lang = "pt" | "en" | "es";

export const locales: { lang: Lang; path: string; code: string; autonym: string; ogLocale: string; htmlLang: string }[] = [
  { lang: "pt", path: "/", code: "PT", autonym: "Português", ogLocale: "pt_BR", htmlLang: "pt-BR" },
  { lang: "en", path: "/en", code: "EN", autonym: "English", ogLocale: "en_US", htmlLang: "en" },
  { lang: "es", path: "/es", code: "ES", autonym: "Español", ogLocale: "es_419", htmlLang: "es" },
];

const pt = {
  meta: {
    title: "Manoa Tour | Reserve seu passeio em Angra dos Reis",
    description: "Passeios compartilhados ou privativos em Angra dos Reis, com valores e agendamento direto pelo WhatsApp.",
    ogTitle: "Manoa Tour | Passeios em Angra dos Reis",
    ogDescription: "Passeios compartilhados ou privativos, com valores e agendamento direto pelo WhatsApp.",
    twitterDescription: "Valores e agendamento do seu passeio direto pelo WhatsApp.",
    ogImageAlt: "Manoa Tour — passeios em Angra dos Reis",
  },
  nav: {
    tours: "Passeios",
    destinations: "Destinos",
    experience: "O Manoa",
    booking: "Reservar",
    whatsapp: "Falar com o Manoa",
    whatsappShort: "WhatsApp ↗",
    homeAria: "Manoa Tour — início",
    homeFooterAria: "Manoa Tour — voltar ao início",
    mainNavAria: "Navegação principal",
    mobileNavAria: "Navegação móvel",
    openMenuAria: "Abrir menu",
    langSwitchAria: "Idioma do site",
  },
  hero: {
    eyebrow: "Passeios em Angra dos Reis",
    titleLine1: "Seu dia em Angra ",
    titleEm: "começa no mar.",
    lead: "Passeios compartilhados ou privativos para conhecer ilhas, praias e águas cristalinas com orientação direta do Manoa.",
    ctaPrimary: "Conhecer os passeios",
    ctaSecondary: "Consultar disponibilidade",
    imageAlt: "Barco do Manoa navegando em águas claras de Angra dos Reis",
    locationLabel: "Destino",
    locationValue: "Angra dos Reis",
    locationSub: "Costa Verde • RJ",
  },
  trustStrip: {
    ariaLabel: "Diferenciais do Manoa",
    items: [
      { title: "Aproximadamente 6 horas", note: "Duração estimada do passeio." },
      { title: "Embarque no Clube ARMC", note: "Local normalmente utilizado." },
      { title: "Escolha orientada", note: "Compartilhado ou privativo para o seu grupo." },
      { title: "Atendimento direto", note: "Valores e agendamento pelo WhatsApp." },
    ],
  },
  tours: {
    eyebrow: "Escolha sua experiência",
    titleLine1: "Dois jeitos de viver",
    titleEm: "o melhor de Angra.",
    intro: "Valores, rotas, vagas e agendamento são confirmados diretamente com o Manoa pelo WhatsApp.",
    shared: {
      kicker: "Experiência em grupo",
      title: "Passeio compartilhado",
      description: "Conheça praias e ilhas ao lado de outros viajantes. Consulte as datas, o roteiro previsto e as vagas disponíveis.",
      tags: ["Experiência em grupo", "Vagas sob consulta", "Roteiro informado antes da saída"],
      cta: "Consultar passeio compartilhado",
      imageAlt: "Águas cristalinas durante passeio em Angra",
    },
    private: {
      kicker: "Experiência exclusiva",
      title: "Passeio privativo",
      description: "Uma experiência reservada para casal, família ou amigos, com mais privacidade e possibilidades de rota alinhadas antes da saída.",
      tags: ["Exclusivo para o grupo", "Mais privacidade", "Rota alinhada com o Manoa"],
      cta: "Consultar passeio privativo",
      imageAlt: "Área interna do barco utilizado nos passeios do Manoa",
    },
    stayNote: {
      location: "Angra dos Reis",
      sublabel: "Orientação local",
      eyebrow: "Parceiros locais",
      title: "Precisa de orientação para escolher onde ficar?",
      description: "O Manoa não oferece hospedagem, mas pode indicar regiões e parceiros conforme o perfil da sua viagem. A contratação é feita diretamente com a hospedagem escolhida.",
      cta: "Pedir indicações",
    },
  },
  destinations: {
    eyebrow: "Cenários da Costa Verde",
    titleLine1: "Um passeio.",
    titleEm: "Muitos tons de azul.",
    intro: "Praias, ilhas e águas transparentes entre Angra e Ilha Grande.",
    cta: "Conversar sobre a rota",
    items: [
      { title: "Ilha Grande", sub: "Praias e Mata Atlântica", alt: "Praia cercada pela Mata Atlântica em Ilha Grande" },
      { title: "Costa Verde", sub: "Mar e natureza", alt: "Águas azuis e natureza na Costa Verde" },
      { title: "Baía de Angra", sub: "Ilhas e embarcações", alt: "Baía e embarcações em Angra dos Reis" },
      { title: "Praias e ilhas", sub: "Águas cristalinas", alt: "Águas cristalinas entre as ilhas de Angra" },
      { title: "Praia Vermelha", sub: "Ilha Grande", alt: "Praia Vermelha, na Ilha Grande" },
      { title: "Angra pelo mar", sub: "Passeio com o Manoa", alt: "Barco do Manoa na baía de Angra dos Reis" },
    ],
  },
  experience: {
    reelAria: "Assistir ao Reel original do Manoa no Instagram",
    reelCaption: "Takes reais • @manoa.tour",
    eyebrow: "Por que escolher o Manoa",
    titleLine1: "Informação clara.",
    titleEm: "Mais tempo para aproveitar.",
    points: [
      { title: "Conhecimento local", description: "Orientação de quem conhece Angra e a região." },
      { title: "Opções para cada grupo", description: "Passeio compartilhado ou privativo, conforme o perfil da viagem." },
      { title: "Tudo alinhado antes", description: "Rota, valores, disponibilidade e agendamento pelo WhatsApp." },
    ],
    onboard: {
      imageAlt: "Área coberta e estrutura interna do barco do Manoa",
      badge: "Estrutura para até 13 passageiros",
      kicker: "Estrutura a bordo",
      title: "Conforto para aproveitar o dia.",
      itemsAria: "Itens disponíveis no barco do Manoa",
      items: ["Colete salva-vidas", "Boias e flutuadores", "Caixa térmica", "Pia com água", "Som Bluetooth", "Banheiro a bordo", "Área coberta", "Até 13 passageiros"],
    },
  },
  testimonials: {
    eyebrow: "Experiências reais",
    titleLine1: "Quem conhece,",
    titleEm: "quer voltar.",
    intro: "Comentários públicos compartilhados por clientes no Instagram do Manoa.",
    trackAria: "Comentários de clientes do Manoa",
    sourceLabel: "Comentário no Instagram",
    linkText: "Ver o Instagram do Manoa",
    items: [
      { quote: "Passeio perfeito, @manoa.tour é o melhor passeio de Angra! Satisfação do início ao fim. Obrigada pelo dia incrível.", author: "@milatalyuli" },
      { quote: "Amamos o passeio, Sr. Silas! Nos sentimos muito bem acolhidos pelo senhor e pelo seu filho. Paraíso é subestimação para estas praias lindas.", author: "@cuorejewels" },
      { quote: "Adoramos os passeios, foram super agradáveis. O barco é excelente e confortável, nos sentimos completamente seguros com o piloto.", author: "@betevcota" },
      { quote: "Só penso em voltar. Indico demais seus passeios, não só pela recepção no seu barco como pela segurança na pilotagem.", author: "@scottyarella" },
      { quote: "Amamos o passeio e o barco. Fomos muito bem recebidos também.", author: "@pereirameri" },
      { quote: "Que passeio top! Obrigada pelo dia incrível que nos proporcionou.", author: "@katiaa_asjlva" },
      { quote: "Foi lindo. Adoramos o passeio.", author: "@daniellarribeirobr" },
      { quote: "Saudades deste lugar. Louco para voltar novamente, principalmente com o Silas, muito atencioso e prestativo.", author: "@geovani.geo.395" },
      { quote: "Ameiiii esse passeio. Top demais. Vocês são 10.", author: "@talita_t_silva" },
      { quote: "Foi maravilhoso! Obrigada a vocês, foi incrível.", author: "@nayracmiranda" },
    ],
  },
  booking: {
    eyebrow: "Planeje seu passeio",
    titleLine1: "Data, grupo e experiência.",
    titleEm: "O Manoa cuida do restante.",
    intro: "Preencha os dados e abra o WhatsApp com uma mensagem organizada para consultar valores e disponibilidade.",
    contactLabel: "WhatsApp oficial",
    form: {
      step1: "01 — Preencha",
      step1Title: "Informe os dados do passeio",
      dateLabel: "Data desejada",
      peopleLabel: "Quantidade de pessoas",
      peoplePlaceholder: "Ex.: 4",
      experienceLabel: "Tipo de experiência",
      experiencePlaceholder: "Selecione uma opção",
      experienceOptions: {
        shared: "Passeio compartilhado",
        private: "Passeio privativo",
        unsure: "Ainda não sei — quero orientação",
      },
      step2: "02 — Mensagem para revisão",
      submit: "Consultar pelo WhatsApp",
      note: "Antes do envio, você poderá revisar e editar a mensagem no WhatsApp.",
      dateFallback: "data a definir",
      peopleFallback: "quantidade a informar",
      peopleSingular: "pessoa",
      peoplePlural: "pessoas",
      experienceFallback: "tipo de experiência a definir",
      greeting: "Olá, Manoa! Gostaria de solicitar informações sobre um passeio.",
      dateIconLabel: "Data",
      peopleIconLabel: "Pessoas",
      experienceIconLabel: "Experiência",
      closing: "Poderia, por favor, informar os valores e a disponibilidade para essa opção?",
    },
  },
  faq: {
    eyebrow: "Antes de reservar",
    titleLine1: "Informações para decidir",
    titleEm: "com tranquilidade.",
    items: [
      { question: "Como faço para agendar um passeio?", answer: "O agendamento é feito diretamente pelo WhatsApp. Informe a data desejada, o número de pessoas e a preferência entre passeio compartilhado ou privativo." },
      { question: "Qual é a duração e o local de embarque?", answer: "O passeio tem duração aproximada de 6 horas. O embarque normalmente acontece no Clube ARMC; o ponto é confirmado com o Manoa antes da saída." },
      { question: "Os valores aparecem no site?", answer: "Não. Valores, vagas e disponibilidade variam conforme a data e a experiência escolhida; a confirmação é feita diretamente pelo WhatsApp." },
      { question: "Posso conversar sobre a rota antes de reservar?", answer: "Sim. O Manoa apresenta as possibilidades de rota para ajudar você a escolher a opção mais adequada ao perfil do grupo." },
      { question: "O Manoa oferece hospedagem?", answer: "O Manoa não oferece hospedagem, mas pode indicar regiões e parceiros locais para você avaliar e contratar diretamente." },
    ],
  },
  finalCta: {
    eyebrow: "Seu passeio em Angra",
    titleLine1: "Pronto para viver",
    titleEm: "um novo tom de azul?",
    description: "Consulte opções, valores e disponibilidade diretamente com o Manoa.",
    cta: "Começar pelo WhatsApp",
  },
  footer: {
    tagline: "Passeios compartilhados • passeios privativos • orientação local",
    instagram: "Instagram ↗",
    whatsapp: "WhatsApp ↗",
  },
  floatingCta: {
    ariaLabel: "Falar com o Manoa pelo WhatsApp",
    title: "Falar com o Manoa",
  },
  whatsapp: {
    general: "Olá, Manoa! Gostaria de conhecer as opções de passeio em Angra dos Reis.",
    shared: "Olá, Manoa! Tenho interesse no passeio compartilhado. Poderia informar as próximas datas, valores e disponibilidade?",
    private: "Olá, Manoa! Tenho interesse em um passeio privativo. Poderia informar as possibilidades de rota, valores e disponibilidade?",
    stay: "Olá, Manoa! Gostaria de receber orientações de regiões e parceiros para hospedagem em Angra dos Reis.",
    route: "Olá, Manoa! Gostaria de conhecer as possibilidades de rota para um passeio em Angra dos Reis.",
  },
};

const en: typeof pt = {
  meta: {
    title: "Manoa Tour | Book Your Tour in Angra dos Reis",
    description: "Shared or private tours in Angra dos Reis, with prices and booking directly via WhatsApp.",
    ogTitle: "Manoa Tour | Tours in Angra dos Reis",
    ogDescription: "Shared or private tours, with prices and booking directly via WhatsApp.",
    twitterDescription: "Prices and booking for your tour, directly via WhatsApp.",
    ogImageAlt: "Manoa Tour — tours in Angra dos Reis",
  },
  nav: {
    tours: "Tours",
    destinations: "Destinations",
    experience: "About Manoa",
    booking: "Book",
    whatsapp: "Chat with Manoa",
    whatsappShort: "WhatsApp ↗",
    homeAria: "Manoa Tour — home",
    homeFooterAria: "Manoa Tour — back to home",
    mainNavAria: "Main navigation",
    mobileNavAria: "Mobile navigation",
    openMenuAria: "Open menu",
    langSwitchAria: "Site language",
  },
  hero: {
    eyebrow: "Tours in Angra dos Reis",
    titleLine1: "Your day in Angra ",
    titleEm: "starts at sea.",
    lead: "Shared or private tours to discover islands, beaches and crystal-clear waters, with direct guidance from Manoa.",
    ctaPrimary: "See the tours",
    ctaSecondary: "Check availability",
    imageAlt: "Manoa's boat sailing in the clear waters of Angra dos Reis",
    locationLabel: "Destination",
    locationValue: "Angra dos Reis",
    locationSub: "Costa Verde • Brazil",
  },
  trustStrip: {
    ariaLabel: "What sets Manoa apart",
    items: [
      { title: "About 6 hours", note: "Estimated tour duration." },
      { title: "Boarding at Clube ARMC", note: "Usual departure point." },
      { title: "Guided choice", note: "Shared or private, for your group." },
      { title: "Direct support", note: "Prices and booking via WhatsApp." },
    ],
  },
  tours: {
    eyebrow: "Choose your experience",
    titleLine1: "Two ways to experience",
    titleEm: "the best of Angra.",
    intro: "Prices, routes, availability and booking are all confirmed directly with Manoa via WhatsApp.",
    shared: {
      kicker: "Group experience",
      title: "Shared tour",
      description: "Discover beaches and islands alongside other travelers. Check dates, the planned route and available spots.",
      tags: ["Group experience", "Spots on request", "Route shared before departure"],
      cta: "Ask about the shared tour",
      imageAlt: "Crystal-clear waters during a tour in Angra",
    },
    private: {
      kicker: "Exclusive experience",
      title: "Private tour",
      description: "A reserved experience for couples, families or friends, with more privacy and route options agreed before departure.",
      tags: ["Exclusive to your group", "More privacy", "Route agreed with Manoa"],
      cta: "Ask about the private tour",
      imageAlt: "Interior area of the boat used on Manoa's tours",
    },
    stayNote: {
      location: "Angra dos Reis",
      sublabel: "Local guidance",
      eyebrow: "Local partners",
      title: "Need help choosing where to stay?",
      description: "Manoa doesn't offer accommodation, but can recommend regions and partners based on your trip profile. Booking is made directly with the accommodation you choose.",
      cta: "Ask for recommendations",
    },
  },
  destinations: {
    eyebrow: "Scenes from the Costa Verde",
    titleLine1: "One tour.",
    titleEm: "Many shades of blue.",
    intro: "Beaches, islands and clear waters between Angra and Ilha Grande.",
    cta: "Chat about the route",
    items: [
      { title: "Ilha Grande", sub: "Beaches and Atlantic Forest", alt: "Beach surrounded by Atlantic Forest in Ilha Grande" },
      { title: "Costa Verde", sub: "Sea and nature", alt: "Blue waters and nature in Costa Verde" },
      { title: "Angra Bay", sub: "Islands and boats", alt: "Bay and boats in Angra dos Reis" },
      { title: "Beaches and islands", sub: "Crystal-clear waters", alt: "Crystal-clear waters between the islands of Angra" },
      { title: "Praia Vermelha", sub: "Ilha Grande", alt: "Praia Vermelha, in Ilha Grande" },
      { title: "Angra by sea", sub: "Touring with Manoa", alt: "Manoa's boat in the bay of Angra dos Reis" },
    ],
  },
  experience: {
    reelAria: "Watch Manoa's original Reel on Instagram",
    reelCaption: "Real moments • @manoa.tour",
    eyebrow: "Why choose Manoa",
    titleLine1: "Clear information.",
    titleEm: "More time to enjoy.",
    points: [
      { title: "Local knowledge", description: "Guidance from people who know Angra and the region." },
      { title: "Options for every group", description: "Shared or private tour, depending on your trip profile." },
      { title: "Everything settled in advance", description: "Route, prices, availability and booking via WhatsApp." },
    ],
    onboard: {
      imageAlt: "Covered area and interior structure of Manoa's boat",
      badge: "Room for up to 13 passengers",
      kicker: "Onboard structure",
      title: "Comfort to enjoy the day.",
      itemsAria: "Items available on Manoa's boat",
      items: ["Life jackets", "Buoys and floats", "Cooler", "Onboard sink", "Bluetooth sound system", "Onboard restroom", "Covered area", "Up to 13 passengers"],
    },
  },
  testimonials: {
    eyebrow: "Real experiences",
    titleLine1: "Once you've been,",
    titleEm: "you'll want to return.",
    intro: "Public comments shared by customers on Manoa's Instagram.",
    trackAria: "Comments from Manoa's customers",
    sourceLabel: "Instagram comment",
    linkText: "View Manoa's Instagram",
    items: [
      { quote: "Perfect tour, @manoa.tour is the best tour in Angra! Satisfying from start to finish. Thank you for the amazing day.", author: "@milatalyuli" },
      { quote: "We loved the tour, Mr. Silas! We felt so welcomed by you and your son. “Paradise” is an understatement for these beautiful beaches.", author: "@cuorejewels" },
      { quote: "We loved the tours, they were so enjoyable. The boat is excellent and comfortable, and we felt completely safe with the captain.", author: "@betevcota" },
      { quote: "All I think about is going back. I highly recommend his tours, not just for the welcome onboard but for the safe piloting too.", author: "@scottyarella" },
      { quote: "We loved the tour and the boat. We were also very well received.", author: "@pereirameri" },
      { quote: "What a great tour! Thank you for the amazing day.", author: "@katiaa_asjlva" },
      { quote: "It was beautiful. We loved the tour.", author: "@daniellarribeirobr" },
      { quote: "Missing this place already. Can't wait to go back, especially with Silas — so attentive and helpful.", author: "@geovani.geo.395" },
      { quote: "Loved this tour so much. Absolutely amazing. You guys are the best.", author: "@talita_t_silva" },
      { quote: "It was wonderful! Thank you all, it was amazing.", author: "@nayracmiranda" },
    ],
  },
  booking: {
    eyebrow: "Plan your tour",
    titleLine1: "Date, group and experience.",
    titleEm: "Manoa takes care of the rest.",
    intro: "Fill in the details and open WhatsApp with an organized message to check prices and availability.",
    contactLabel: "Official WhatsApp",
    form: {
      step1: "01 — Fill in",
      step1Title: "Enter your tour details",
      dateLabel: "Preferred date",
      peopleLabel: "Number of people",
      peoplePlaceholder: "E.g.: 4",
      experienceLabel: "Type of experience",
      experiencePlaceholder: "Select an option",
      experienceOptions: {
        shared: "Shared tour",
        private: "Private tour",
        unsure: "Not sure yet — I'd like guidance",
      },
      step2: "02 — Message to review",
      submit: "Ask via WhatsApp",
      note: "Before sending, you'll be able to review and edit the message in WhatsApp.",
      dateFallback: "date to be defined",
      peopleFallback: "number to be provided",
      peopleSingular: "person",
      peoplePlural: "people",
      experienceFallback: "experience type to be defined",
      greeting: "Hi Manoa! I'd like to get information about a tour.",
      dateIconLabel: "Date",
      peopleIconLabel: "People",
      experienceIconLabel: "Experience",
      closing: "Could you please let me know the prices and availability for this option?",
    },
  },
  faq: {
    eyebrow: "Before booking",
    titleLine1: "Information to help you decide",
    titleEm: "with confidence.",
    items: [
      { question: "How do I book a tour?", answer: "Booking is done directly via WhatsApp. Share your preferred date, number of people and whether you'd like a shared or private tour." },
      { question: "What's the duration and boarding location?", answer: "The tour lasts approximately 6 hours. Boarding usually takes place at Clube ARMC; the exact point is confirmed with Manoa before departure." },
      { question: "Are prices shown on the website?", answer: "No. Prices, spots and availability vary depending on the date and the chosen experience; confirmation is done directly via WhatsApp." },
      { question: "Can I discuss the route before booking?", answer: "Yes. Manoa will walk you through the route options to help you choose the best fit for your group." },
      { question: "Does Manoa offer accommodation?", answer: "Manoa doesn't offer accommodation, but can point you to regions and local partners for you to evaluate and book directly." },
    ],
  },
  finalCta: {
    eyebrow: "Your tour in Angra",
    titleLine1: "Ready to experience",
    titleEm: "a new shade of blue?",
    description: "Check options, prices and availability directly with Manoa.",
    cta: "Start on WhatsApp",
  },
  footer: {
    tagline: "Shared tours • private tours • local guidance",
    instagram: "Instagram ↗",
    whatsapp: "WhatsApp ↗",
  },
  floatingCta: {
    ariaLabel: "Chat with Manoa on WhatsApp",
    title: "Chat with Manoa",
  },
  whatsapp: {
    general: "Hi Manoa! I'd like to learn about the tour options in Angra dos Reis.",
    shared: "Hi Manoa! I'm interested in the shared tour. Could you share the upcoming dates, prices and availability?",
    private: "Hi Manoa! I'm interested in a private tour. Could you share the possible routes, prices and availability?",
    stay: "Hi Manoa! I'd like some guidance on regions and partners for accommodation in Angra dos Reis.",
    route: "Hi Manoa! I'd like to learn about the possible routes for a tour in Angra dos Reis.",
  },
};

const es: typeof pt = {
  meta: {
    title: "Manoa Tour | Reserva tu paseo en Angra dos Reis",
    description: "Paseos compartidos o privados en Angra dos Reis, con valores y reservas directas por WhatsApp.",
    ogTitle: "Manoa Tour | Paseos en Angra dos Reis",
    ogDescription: "Paseos compartidos o privados, con valores y reservas directas por WhatsApp.",
    twitterDescription: "Valores y reserva de tu paseo directamente por WhatsApp.",
    ogImageAlt: "Manoa Tour — paseos en Angra dos Reis",
  },
  nav: {
    tours: "Paseos",
    destinations: "Destinos",
    experience: "El Manoa",
    booking: "Reservar",
    whatsapp: "Hablar con Manoa",
    whatsappShort: "WhatsApp ↗",
    homeAria: "Manoa Tour — inicio",
    homeFooterAria: "Manoa Tour — volver al inicio",
    mainNavAria: "Navegación principal",
    mobileNavAria: "Navegación móvil",
    openMenuAria: "Abrir menú",
    langSwitchAria: "Idioma del sitio",
  },
  hero: {
    eyebrow: "Paseos en Angra dos Reis",
    titleLine1: "Tu día en Angra ",
    titleEm: "empieza en el mar.",
    lead: "Paseos compartidos o privados para conocer islas, playas y aguas cristalinas con orientación directa de Manoa.",
    ctaPrimary: "Conocer los paseos",
    ctaSecondary: "Consultar disponibilidad",
    imageAlt: "El barco de Manoa navegando en aguas claras de Angra dos Reis",
    locationLabel: "Destino",
    locationValue: "Angra dos Reis",
    locationSub: "Costa Verde • RJ",
  },
  trustStrip: {
    ariaLabel: "Los diferenciales de Manoa",
    items: [
      { title: "Aproximadamente 6 horas", note: "Duración estimada del paseo." },
      { title: "Embarque en el Clube ARMC", note: "Punto de salida habitual." },
      { title: "Elección orientada", note: "Compartido o privado para tu grupo." },
      { title: "Atención directa", note: "Valores y reservas por WhatsApp." },
    ],
  },
  tours: {
    eyebrow: "Elige tu experiencia",
    titleLine1: "Dos formas de vivir",
    titleEm: "lo mejor de Angra.",
    intro: "Valores, rutas, cupos y reservas se confirman directamente con Manoa por WhatsApp.",
    shared: {
      kicker: "Experiencia en grupo",
      title: "Paseo compartido",
      description: "Conoce playas e islas junto a otros viajeros. Consulta las fechas, el itinerario previsto y los cupos disponibles.",
      tags: ["Experiencia en grupo", "Cupos a consultar", "Itinerario informado antes de salir"],
      cta: "Consultar paseo compartido",
      imageAlt: "Aguas cristalinas durante un paseo en Angra",
    },
    private: {
      kicker: "Experiencia exclusiva",
      title: "Paseo privado",
      description: "Una experiencia reservada para parejas, familias o amigos, con más privacidad y posibilidades de ruta acordadas antes de salir.",
      tags: ["Exclusivo para el grupo", "Más privacidad", "Ruta acordada con Manoa"],
      cta: "Consultar paseo privado",
      imageAlt: "Área interior del barco utilizado en los paseos de Manoa",
    },
    stayNote: {
      location: "Angra dos Reis",
      sublabel: "Orientación local",
      eyebrow: "Socios locales",
      title: "¿Necesitas orientación para elegir dónde alojarte?",
      description: "Manoa no ofrece hospedaje, pero puede indicar regiones y socios según el perfil de tu viaje. La contratación se hace directamente con el hospedaje elegido.",
      cta: "Pedir recomendaciones",
    },
  },
  destinations: {
    eyebrow: "Escenarios de la Costa Verde",
    titleLine1: "Un paseo.",
    titleEm: "Muchos tonos de azul.",
    intro: "Playas, islas y aguas transparentes entre Angra e Ilha Grande.",
    cta: "Conversar sobre la ruta",
    items: [
      { title: "Ilha Grande", sub: "Playas y Mata Atlántica", alt: "Playa rodeada de Mata Atlántica en Ilha Grande" },
      { title: "Costa Verde", sub: "Mar y naturaleza", alt: "Aguas azules y naturaleza en la Costa Verde" },
      { title: "Bahía de Angra", sub: "Islas y embarcaciones", alt: "Bahía y embarcaciones en Angra dos Reis" },
      { title: "Playas e islas", sub: "Aguas cristalinas", alt: "Aguas cristalinas entre las islas de Angra" },
      { title: "Praia Vermelha", sub: "Ilha Grande", alt: "Praia Vermelha, en Ilha Grande" },
      { title: "Angra por el mar", sub: "Paseo con Manoa", alt: "El barco de Manoa en la bahía de Angra dos Reis" },
    ],
  },
  experience: {
    reelAria: "Ver el Reel original de Manoa en Instagram",
    reelCaption: "Momentos reales • @manoa.tour",
    eyebrow: "Por qué elegir a Manoa",
    titleLine1: "Información clara.",
    titleEm: "Más tiempo para disfrutar.",
    points: [
      { title: "Conocimiento local", description: "Orientación de quienes conocen Angra y la región." },
      { title: "Opciones para cada grupo", description: "Paseo compartido o privado, según el perfil del viaje." },
      { title: "Todo acordado antes", description: "Ruta, valores, disponibilidad y reserva por WhatsApp." },
    ],
    onboard: {
      imageAlt: "Área cubierta y estructura interna del barco de Manoa",
      badge: "Estructura para hasta 13 pasajeros",
      kicker: "Estructura a bordo",
      title: "Comodidad para disfrutar el día.",
      itemsAria: "Elementos disponibles en el barco de Manoa",
      items: ["Chalecos salvavidas", "Boyas y flotadores", "Caja térmica", "Lavabo con agua", "Sonido Bluetooth", "Baño a bordo", "Área cubierta", "Hasta 13 pasajeros"],
    },
  },
  testimonials: {
    eyebrow: "Experiencias reales",
    titleLine1: "Quien lo conoce,",
    titleEm: "quiere volver.",
    intro: "Comentarios públicos compartidos por clientes en el Instagram de Manoa.",
    trackAria: "Comentarios de clientes de Manoa",
    sourceLabel: "Comentario en Instagram",
    linkText: "Ver el Instagram de Manoa",
    items: [
      { quote: "Paseo perfecto, ¡@manoa.tour es el mejor paseo de Angra! Satisfacción de principio a fin. Gracias por el día increíble.", author: "@milatalyuli" },
      { quote: "¡Amamos el paseo, Sr. Silas! Nos sentimos muy bien recibidos por usted y su hijo. “Paraíso” se queda corto para estas playas tan hermosas.", author: "@cuorejewels" },
      { quote: "Adoramos los paseos, fueron súper agradables. El barco es excelente y cómodo, nos sentimos completamente seguros con el piloto.", author: "@betevcota" },
      { quote: "Solo pienso en volver. Recomiendo muchísimo sus paseos, no solo por la recepción a bordo sino por la seguridad al pilotar.", author: "@scottyarella" },
      { quote: "Amamos el paseo y el barco. También fuimos muy bien recibidos.", author: "@pereirameri" },
      { quote: "¡Qué paseo tan bueno! Gracias por el día increíble que nos regalaron.", author: "@katiaa_asjlva" },
      { quote: "Fue hermoso. Amamos el paseo.", author: "@daniellarribeirobr" },
      { quote: "Extraño este lugar. Muero por volver, especialmente con Silas, tan atento y servicial.", author: "@geovani.geo.395" },
      { quote: "Me encantóoo este paseo. Buenísimo. Ustedes son un 10.", author: "@talita_t_silva" },
      { quote: "¡Fue maravilloso! Gracias a ustedes, fue increíble.", author: "@nayracmiranda" },
    ],
  },
  booking: {
    eyebrow: "Planifica tu paseo",
    titleLine1: "Fecha, grupo y experiencia.",
    titleEm: "Manoa se encarga del resto.",
    intro: "Completa los datos y abre WhatsApp con un mensaje organizado para consultar valores y disponibilidad.",
    contactLabel: "WhatsApp oficial",
    form: {
      step1: "01 — Completa",
      step1Title: "Indica los datos del paseo",
      dateLabel: "Fecha deseada",
      peopleLabel: "Cantidad de personas",
      peoplePlaceholder: "Ej.: 4",
      experienceLabel: "Tipo de experiencia",
      experiencePlaceholder: "Selecciona una opción",
      experienceOptions: {
        shared: "Paseo compartido",
        private: "Paseo privado",
        unsure: "Aún no lo sé — quiero orientación",
      },
      step2: "02 — Mensaje para revisar",
      submit: "Consultar por WhatsApp",
      note: "Antes de enviarlo, podrás revisar y editar el mensaje en WhatsApp.",
      dateFallback: "fecha por definir",
      peopleFallback: "cantidad por indicar",
      peopleSingular: "persona",
      peoplePlural: "personas",
      experienceFallback: "tipo de experiencia por definir",
      greeting: "¡Hola, Manoa! Me gustaría solicitar información sobre un paseo.",
      dateIconLabel: "Fecha",
      peopleIconLabel: "Personas",
      experienceIconLabel: "Experiencia",
      closing: "¿Podrías indicarme los valores y la disponibilidad para esta opción?",
    },
  },
  faq: {
    eyebrow: "Antes de reservar",
    titleLine1: "Información para decidir",
    titleEm: "con tranquilidad.",
    items: [
      { question: "¿Cómo hago para reservar un paseo?", answer: "La reserva se hace directamente por WhatsApp. Indica la fecha deseada, el número de personas y la preferencia entre paseo compartido o privado." },
      { question: "¿Cuál es la duración y el lugar de embarque?", answer: "El paseo dura aproximadamente 6 horas. El embarque normalmente ocurre en el Clube ARMC; el punto se confirma con Manoa antes de salir." },
      { question: "¿Los valores aparecen en el sitio?", answer: "No. Los valores, cupos y disponibilidad varían según la fecha y la experiencia elegida; la confirmación se hace directamente por WhatsApp." },
      { question: "¿Puedo conversar sobre la ruta antes de reservar?", answer: "Sí. Manoa te presenta las posibilidades de ruta para ayudarte a elegir la opción más adecuada para tu grupo." },
      { question: "¿Manoa ofrece hospedaje?", answer: "Manoa no ofrece hospedaje, pero puede indicarte regiones y socios locales para que evalúes y contrates directamente." },
    ],
  },
  finalCta: {
    eyebrow: "Tu paseo en Angra",
    titleLine1: "¿Listo para vivir",
    titleEm: "un nuevo tono de azul?",
    description: "Consulta opciones, valores y disponibilidad directamente con Manoa.",
    cta: "Empezar por WhatsApp",
  },
  footer: {
    tagline: "Paseos compartidos • paseos privados • orientación local",
    instagram: "Instagram ↗",
    whatsapp: "WhatsApp ↗",
  },
  floatingCta: {
    ariaLabel: "Hablar con Manoa por WhatsApp",
    title: "Hablar con Manoa",
  },
  whatsapp: {
    general: "¡Hola, Manoa! Me gustaría conocer las opciones de paseo en Angra dos Reis.",
    shared: "¡Hola, Manoa! Me interesa el paseo compartido. ¿Podrías indicarme las próximas fechas, valores y disponibilidad?",
    private: "¡Hola, Manoa! Me interesa un paseo privado. ¿Podrías indicarme las posibilidades de ruta, valores y disponibilidad?",
    stay: "¡Hola, Manoa! Me gustaría recibir orientación sobre regiones y socios de hospedaje en Angra dos Reis.",
    route: "¡Hola, Manoa! Me gustaría conocer las posibilidades de ruta para un paseo en Angra dos Reis.",
  },
};

export const content: Record<Lang, typeof pt> = { pt, en, es };
